/**
 * Write the tag lexicon and axis metadata to JSON, for the Python engine.
 *
 * The lexicon is hand-authored data that happens to live in TypeScript. Two
 * copies of 180 hand-tuned tag profiles would drift the first time one is
 * edited, and the drift would show up as recommendations that differ by route
 * rather than as an error.
 */
import { writeFileSync } from 'node:fs';
import { TAG_LEXICON, ERA_MIN, ERA_MAX } from '../src/data/lexicon';
import { AXIS_WEIGHT, WEIGHT_NORM, TUNING } from '../src/engine/recommend';
import { AXES } from '../src/data/schema';

const out = {
  note: 'Generated by scripts/dump-lexicon.ts. Edit src/data/lexicon.ts, not this.',
  axes: AXES,
  axisWeight: AXIS_WEIGHT,
  weightNorm: WEIGHT_NORM,
  eraMin: ERA_MIN,
  eraMax: ERA_MAX,
  lexicon: TAG_LEXICON,
};
// Fail loudly on a missing value. JSON.stringify drops undefined silently, so
// an import that moved would produce a file that looks fine and scores wrong.
for (const [k, v] of Object.entries(out)) {
  if (v === undefined) throw new Error(`dump-lexicon: ${k} is undefined`);
}
if (Object.keys(out.lexicon).length < 100) throw new Error('lexicon looks truncated');
if (!Number.isFinite(out.weightNorm)) throw new Error('weightNorm is not a number');

// TUNING goes out too, so the server engine reads the client's values rather
// than restating them. Two copies of a dozen tuned constants drift the first
// time one is swept, and the drift shows up as recommendations that differ by
// route.
writeFileSync(new URL('../data/tuning.json', import.meta.url), JSON.stringify(TUNING, null, 1));

const path = new URL('../data/lexicon.json', import.meta.url);
writeFileSync(path, JSON.stringify(out, null, 1));
console.log(`${Object.keys(TAG_LEXICON).length} tags -> data/lexicon.json`);
console.log(`${Object.keys(TUNING).length} tuning constants -> data/tuning.json`);
