#!/usr/bin/env python3
"""
Freeze the engine's population statistics, so both engines agree.

Axis spread and tag informativeness describe a population, not a record. The
client measures them over the 12,000 albums it ships; a server-side engine
would measure them over 100,931. Same album, different distance, different
overlap — and the divergence would look like a bad port rather than two
correct implementations reading different worlds.

So they are computed once here, over the whole database, and both sides load
the result. Same reasoning that made popularity and quality absolute: a number
that depends on who is asking cannot be checked across the wire.

    .venv/bin/python scripts/export_engine_constants.py
"""
from __future__ import annotations

import json
import math
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

import db  # noqa: E402

ROOT = HERE.parent
LEXICON = json.loads((ROOT / "data" / "lexicon.json").read_text())
OUT = ROOT / "data" / "engine-constants.json"

AXES = LEXICON["axes"]
TAG_LEXICON = LEXICON["lexicon"]
ERA_MIN, ERA_MAX = LEXICON["eraMin"], LEXICON["eraMax"]

# Mirrors NON_MUSICAL in src/data/catalog.ts.
NON_MUSICAL = [
    "american", "usa", "us", "british", "uk", "english", "german", "deutsch",
    "french", "japanese", "canadian", "swedish", "australian", "norwegian",
    "finnish", "polish", "russian", "italian", "spanish", "dutch", "danish",
    "belgian", "irish", "scottish", "américain", "britannique", "allemand",
    "seen live", "favourites", "favorites", "owned", "vinyl", "spotify",
]
NON_MUSICAL_RE = re.compile(r"^\d{4}$|charts?$|^jahrescharts|^offizielle|^top \d+$", re.I)


def musical(tag: str) -> bool:
    return tag not in NON_MUSICAL and not NON_MUSICAL_RE.match(tag)


def clamp01(v: float) -> float:
    return max(0.0, min(1.0, v))


def derive_vector(tags: list[tuple[str, int]], year: int | None) -> dict[str, float]:
    sums = {a: 0.0 for a in AXES}
    weights = {a: 0.0 for a in AXES}
    for tag, count in tags:
        profile = TAG_LEXICON.get(tag.lower().strip())
        if not profile:
            continue
        w = math.sqrt(max(1, count))
        for axis, value in profile.items():
            sums[axis] += value * w
            weights[axis] += w
    v = {a: clamp01(sums[a] / weights[a]) if weights[a] > 0 else 0.5 for a in AXES}
    v["era"] = 0.5 if year is None else clamp01((year - ERA_MIN) / (ERA_MAX - ERA_MIN))
    return v


def main() -> int:
    conn = db.connect()
    tags: dict[str, list[tuple[str, int]]] = {}
    for r in conn.execute("SELECT item_id, tag, count FROM item_tags"):
        tags.setdefault(r["item_id"], []).append((r["tag"], r["count"] or 1))

    rows = conn.execute(
        """SELECT i.id, i.year_start FROM items i
           WHERE i.art_url IS NOT NULL
             AND EXISTS (SELECT 1 FROM item_tags t WHERE t.item_id = i.id)"""
    ).fetchall()
    print(f"computing over {len(rows):,} albums")

    # Axis spread.
    vectors = [derive_vector(tags.get(r["id"], []), r["year_start"]) for r in rows]
    axis_sd = {}
    for a in AXES:
        vals = [v[a] for v in vectors]
        mean = sum(vals) / len(vals)
        var = sum((x - mean) ** 2 for x in vals) / len(vals)
        axis_sd[a] = round(max(0.02, math.sqrt(var)), 6)

    # Tag informativeness, over musical tags only.
    df: dict[str, int] = {}
    for item_tags in tags.values():
        for tag, _ in set(item_tags):
            if musical(tag):
                df[tag] = df.get(tag, 0) + 1
    n = max(1, len(rows))
    tag_idf = {t: round(math.log((n + 1) / (c + 1)), 6) for t, c in df.items()}
    mean_idf = round(sum(tag_idf.values()) / max(1, len(tag_idf)), 6)

    payload = {
        "note": "Generated by scripts/export_engine_constants.py. Both engines read this.",
        "albums": len(rows),
        "axisSd": axis_sd,
        "meanIdf": mean_idf,
        "nonMusical": NON_MUSICAL,
        "tagIdf": tag_idf,
        # Kept beside them so the server engine does not restate TUNING and
        # drift from it; the client still owns the values.
        "tuning": json.loads((ROOT / "data" / "tuning.json").read_text())
        if (ROOT / "data" / "tuning.json").exists() else {},
    }
    OUT.write_text(json.dumps(payload, indent=1))
    print(f"axis sd: { {k: round(v, 3) for k, v in axis_sd.items()} }")
    print(f"{len(tag_idf):,} tags, mean idf {mean_idf} -> {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
